export const LIMITS = {
  QUEUE: {
    MAX_CONCURRENT_PER_USER: 50,
    MAX_CONCURRENT_PER_IP: 100,
    MAX_DEPTH: 1000,
    TIMEOUT_MS: 30_000,
    SLOT_TTL_BUFFER_SECONDS: 5,
  },
  INPUT: {
    USERNAME_MAX_LENGTH: 50,
    BIO_MAX_LENGTH: 500,
    POST_MAX_LENGTH: 280,
  },
  SESSION: {
    MAX_PER_USER: 2,
    MAX_LOGIN_ATTEMPTS: 3,
    LOCKOUT_DURATION_MINUTES: 60,
  },
} as const;

