export const VALIDATION = {
  USERNAME_MIN: 3,
  USERNAME_MAX: 50,
  POST_CONTENT_MAX: 280,
  COMMENT_CONTENT_MAX: 500,
  BIO_MAX: 500,
  NAME_MAX: 100,
  CONTACT_NAME_MAX: 50,
  CONTACT_NOTES_MAX: 200,
  PROFILE_IMAGE_MAX_SIZE: 5 * 1024 * 1024,
  SEARCH_QUERY_MAX: 50,
  VIP_DESCRIPTION_MAX: 1000,
  IMAGES_PER_POST_MAX: 4,
  MAX_SLIPPAGE_PERCENT: 5,
  MAX_SLIPPAGE_BPS: 500,
  PIN: {
    MIN_LENGTH: 4,
    MAX_LENGTH: 6,
    PATTERN: /^\d+$/,
  },
  SOLANA_ADDRESS: {
    PATTERN: /^[1-9A-HJ-NP-Za-km-z]{32,44}$/,
    MIN_LENGTH: 32,
    MAX_LENGTH: 44,
  },
  AMOUNT: {
    MIN_SOL: 0.00001,
    MAX_DECIMALS: 9,
  },
} as const;

