import { useState } from 'react';
import createContextHook from '@/lib/create-context-hook';

export interface TraderProfile {
  id: string;
  username: string;
  profileImage?: string;
  isVerified: boolean;
  badge?: 'elite' | 'general' | 'pro' | 'vip';
  followers: number;
  following: number;
  copyTraders: number;
  roi30d: number;
  vipFollowers: number;
  pnl24h: number;
  maxDrawdown: number;
  winRate: number;
  vipPrice?: number;
}

export interface SocialPost {
  id: string;
  username: string;
  profileImage?: string;
  isVerified: boolean;
  content: string;
  timestamp: string;
  likes: number;
  comments: number;
  reposts: number;
  mentionedToken?: string;
  visibility?: 'public' | 'vip' | 'followers';
}

export const [SocialProvider, useSocial] = createContextHook(() => {
  const [followedUsers, setFollowedUsers] = useState<string[]>(['alphaWolf', 'ghostxsol']);

  // Get trader profile by username
  const getTraderProfile = (username: string): TraderProfile | undefined => {
    return mockTraders.find(trader => trader.username === username);
  };

  // Follow/unfollow user
  const toggleFollow = (username: string) => {
    setFollowedUsers(prev => {
      if (prev.includes(username)) {
        return prev.filter(user => user !== username);
      } else {
        return [...prev, username];
      }
    });
  };

  // Check if user is followed
  const isFollowing = (username: string): boolean => {
    return followedUsers.includes(username);
  };

  return {
    traders: mockTraders,
    posts: mockPosts,
    getTraderProfile,
    toggleFollow,
    isFollowing,
    followedUsers,
  };
});

// Mock trader profiles
const mockTraders: TraderProfile[] = [
  {
    id: '1',
    username: 'ghostxsol',
    profileImage: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61',
    isVerified: true,
    badge: 'elite',
    followers: 8421,
    following: 200,
    copyTraders: 3122,
    roi30d: 143.2,
    vipFollowers: 203,
    pnl24h: 12410.40,
    maxDrawdown: -5.3,
    winRate: 81,

    vipPrice: 49,
  },
  {
    id: '2',
    username: 'alphaWolf',
    profileImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e',
    isVerified: true,
    badge: 'pro',
    followers: 5234,
    following: 150,
    copyTraders: 1876,
    roi30d: 89.7,
    vipFollowers: 156,
    pnl24h: 8750.20,
    maxDrawdown: -8.1,
    winRate: 74,

    vipPrice: 39,
  },
  {
    id: '3',
    username: 'cryptoQueen',
    profileImage: 'https://images.unsplash.com/photo-1494790108755-2616b612b786',
    isVerified: true,
    badge: 'general',
    followers: 3456,
    following: 89,
    copyTraders: 1234,
    roi30d: 67.4,
    vipFollowers: 98,
    pnl24h: 5420.80,
    maxDrawdown: -12.5,
    winRate: 68,

    vipPrice: 29,
  },
  {
    id: '4',
    username: 'solanaKing',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
    isVerified: true,
    badge: 'elite',
    followers: 12543,
    following: 45,
    copyTraders: 4567,
    roi30d: 198.5,
    vipFollowers: 345,
    pnl24h: 18920.50,
    maxDrawdown: -3.2,
    winRate: 87,

    vipPrice: 79,
  },
  {
    id: '5',
    username: 'memeLord',
    profileImage: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde',
    isVerified: false,
    badge: 'general',
    followers: 2134,
    following: 234,
    copyTraders: 567,
    roi30d: 45.8,
    vipFollowers: 34,
    pnl24h: 2340.60,
    maxDrawdown: -18.7,
    winRate: 62,

    vipPrice: 19,
  },
  {
    id: '6',
    username: 'bhavanisingh',
    profileImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80',
    isVerified: true,
    badge: 'pro',
    followers: 4567,
    following: 123,
    copyTraders: 1890,
    roi30d: 92.3,
    vipFollowers: 178,
    pnl24h: 9234.70,
    maxDrawdown: -6.8,
    winRate: 76,

    vipPrice: 42,
  },
  {
    id: '7',
    username: 'degenTrader',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
    isVerified: false,
    badge: 'general',
    followers: 1876,
    following: 345,
    copyTraders: 432,
    roi30d: 34.6,
    vipFollowers: 23,
    pnl24h: 1567.30,
    maxDrawdown: -22.1,
    winRate: 58,

    vipPrice: 15,
  },
  {
    id: '8',
    username: 'nftWhale',
    profileImage: 'https://images.unsplash.com/photo-1463453091185-61582044d556',
    isVerified: true,
    badge: 'vip',
    followers: 6789,
    following: 67,
    copyTraders: 2345,
    roi30d: 156.8,
    vipFollowers: 289,
    pnl24h: 15678.90,
    maxDrawdown: -4.2,
    winRate: 83,

    vipPrice: 65,
  },
  {
    id: '9',
    username: 'moonBoy',
    profileImage: 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128',
    isVerified: false,
    badge: 'general',
    followers: 987,
    following: 456,
    copyTraders: 234,
    roi30d: 23.4,
    vipFollowers: 12,
    pnl24h: 567.80,
    maxDrawdown: -28.5,
    winRate: 52,

    vipPrice: 12,
  },
  {
    id: '10',
    username: 'solanaGuru',
    profileImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7',
    isVerified: true,
    badge: 'elite',
    followers: 9876,
    following: 89,
    copyTraders: 3456,
    roi30d: 187.9,
    vipFollowers: 312,
    pnl24h: 17890.60,
    maxDrawdown: -2.8,
    winRate: 89,

    vipPrice: 72,
  },
  {
    id: '11',
    username: 'cryptoPrincess',
    profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2',
    isVerified: true,
    badge: 'pro',
    followers: 3789,
    following: 156,
    copyTraders: 1456,
    roi30d: 78.5,
    vipFollowers: 134,
    pnl24h: 7234.50,
    maxDrawdown: -9.3,
    winRate: 71,

    vipPrice: 35,
  },
  {
    id: '12',
    username: 'diamondHands',
    profileImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d',
    isVerified: true,
    badge: 'vip',
    followers: 7654,
    following: 34,
    copyTraders: 2789,
    roi30d: 234.7,
    vipFollowers: 456,
    pnl24h: 23456.80,
    maxDrawdown: -1.9,
    winRate: 92,

    vipPrice: 89,
  },
];

// Mock data
const mockPosts: SocialPost[] = [
  {
    id: '1',
    username: 'alphaWolf',
    profileImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e',
    isVerified: true,
    content: 'SOL is looking bullish. Entered at $145. #solana #breakout',
    timestamp: '2h ago',
    likes: 302,
    comments: 42,
    reposts: 31,
    mentionedToken: 'SOL',
    visibility: 'public',
  },
  {
    id: '2',
    username: 'ghostxsol',
    profileImage: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61',
    isVerified: true,
    content: 'SOL ready to breakout. Target $180 by end of week. $SOL',
    timestamp: '4h ago',
    likes: 211,
    comments: 12,
    reposts: 8,
    mentionedToken: 'SOL',
    visibility: 'public',
  },
  {
    id: '3',
    username: 'bhavanisingh',
    profileImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80',
    isVerified: true,
    content: 'Loading up on $WIF. This meme has legs! #dogwifhat',
    timestamp: '6h ago',
    likes: 98,
    comments: 12,
    reposts: 20,
    mentionedToken: 'WIF',
    visibility: 'followers',
  },
  {
    id: '4',
    username: 'cryptoQueen',
    profileImage: 'https://images.unsplash.com/photo-1494790108755-2616b612b786',
    isVerified: true,
    content: 'BONK is the next 100x. Don\'t miss out! $BONK #solana',
    timestamp: '1d ago',
    likes: 45,
    comments: 8,
    reposts: 5,
    mentionedToken: 'BONK',
    visibility: 'public',
  },
  {
    id: '5',
    username: 'ghostxsol',
    profileImage: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61',
    isVerified: true,
    content: '#vip JUP accumulation zone. Loading up under $1. $JUP',
    timestamp: '1d ago',
    likes: 156,
    comments: 23,
    reposts: 14,
    mentionedToken: 'JUP',
    visibility: 'vip',
  },
  {
    id: '6',
    username: 'solanaKing',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
    isVerified: true,
    content: 'Major breakout incoming on $RNDR. Technical analysis shows strong support at $8.50. Target $15 by month end.',
    timestamp: '3h ago',
    likes: 445,
    comments: 67,
    reposts: 89,
    mentionedToken: 'RNDR',
    visibility: 'public',
  },
  {
    id: '7',
    username: 'memeLord',
    profileImage: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde',
    isVerified: false,
    content: 'PEPE season is here! 🐸 Just loaded my bags. This is not financial advice but... 🚀',
    timestamp: '5h ago',
    likes: 123,
    comments: 34,
    reposts: 56,
    mentionedToken: 'PEPE',
    visibility: 'public',
  },
  {
    id: '8',
    username: 'nftWhale',
    profileImage: 'https://images.unsplash.com/photo-1463453091185-61582044d556',
    isVerified: true,
    content: 'Just picked up another blue chip NFT. Floor is lava on this collection 🔥 #NFT #solana',
    timestamp: '1h ago',
    likes: 234,
    comments: 45,
    reposts: 67,
    visibility: 'public',
  },
  {
    id: '9',
    username: 'solanaGuru',
    profileImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7',
    isVerified: true,
    content: 'DeFi summer is back! Yield farming opportunities are insane right now. $RAY $ORCA',
    timestamp: '3h ago',
    likes: 567,
    comments: 89,
    reposts: 123,
    mentionedToken: 'RAY',
    visibility: 'public',
  },
  {
    id: '10',
    username: 'cryptoPrincess',
    profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2',
    isVerified: true,
    content: 'Found a hidden gem 💎 $SAMO is about to explode. Thank me later! #SamoyCoin',
    timestamp: '7h ago',
    likes: 189,
    comments: 34,
    reposts: 56,
    mentionedToken: 'SAMO',
    visibility: 'followers',
  },
  {
    id: '11',
    username: 'diamondHands',
    profileImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d',
    isVerified: true,
    content: '#vip Exclusive alpha: Major partnership announcement coming for $STEP. Loading up now.',
    timestamp: '4h ago',
    likes: 345,
    comments: 78,
    reposts: 91,
    mentionedToken: 'STEP',
    visibility: 'vip',
  },
  {
    id: '12',
    username: 'degenTrader',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
    isVerified: false,
    content: 'YOLO\'d into $MYRO. Either lambo or ramen 🍜 #degen #memecoin',
    timestamp: '8h ago',
    likes: 67,
    comments: 23,
    reposts: 12,
    mentionedToken: 'MYRO',
    visibility: 'public',
  },
  {
    id: '13',
    username: 'moonBoy',
    profileImage: 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128',
    isVerified: false,
    content: 'To the moon! 🚀🌙 $DOGE is ready for another run. Elon tweet incoming?',
    timestamp: '12h ago',
    likes: 89,
    comments: 45,
    reposts: 23,
    mentionedToken: 'DOGE',
    visibility: 'public',
  },
  {
    id: '14',
    username: 'alphaWolf',
    profileImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e',
    isVerified: true,
    content: 'Market structure looking strong. Accumulation phase complete. Next leg up incoming 📈',
    timestamp: '5h ago',
    likes: 456,
    comments: 67,
    reposts: 89,
    visibility: 'public',
  },
  {
    id: '15',
    username: 'bhavanisingh',
    profileImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80',
    isVerified: true,
    content: 'Technical analysis update: $SOL forming a perfect cup and handle pattern. Breakout target $200+',
    timestamp: '9h ago',
    likes: 234,
    comments: 56,
    reposts: 78,
    mentionedToken: 'SOL',
    visibility: 'public',
  },
  {
    id: '16',
    username: 'ghostxsol',
    profileImage: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61',
    isVerified: true,
    content: 'Whale alert! 🐋 Someone just moved 100M $USDC to Solana. Big things coming...',
    timestamp: '6h ago',
    likes: 678,
    comments: 123,
    reposts: 234,
    mentionedToken: 'USDC',
    visibility: 'public',
  },
  {
    id: '17',
    username: 'cryptoQueen',
    profileImage: 'https://images.unsplash.com/photo-1494790108755-2616b612b786',
    isVerified: true,
    content: 'Ladies in crypto unite! 👑 Building the future one trade at a time. #WomenInCrypto',
    timestamp: '10h ago',
    likes: 345,
    comments: 89,
    reposts: 156,
    visibility: 'public',
  },
  {
    id: '18',
    username: 'solanaKing',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
    isVerified: true,
    content: '#vip Exclusive: New Solana validator coming online. Staking rewards about to increase 📊',
    timestamp: '2h ago',
    likes: 567,
    comments: 134,
    reposts: 89,
    visibility: 'vip',
  },
  {
    id: '19',
    username: 'memeLord',
    profileImage: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde',
    isVerified: false,
    content: 'When you buy the dip but it keeps dipping 😭 HODL strong brothers! 💪',
    timestamp: '14h ago',
    likes: 234,
    comments: 67,
    reposts: 45,
    visibility: 'public',
  },
  {
    id: '20',
    username: 'nftWhale',
    profileImage: 'https://images.unsplash.com/photo-1463453091185-61582044d556',
    isVerified: true,
    content: 'NFT market heating up! 🔥 Floor prices rising across all major collections. Time to buy?',
    timestamp: '11h ago',
    likes: 456,
    comments: 78,
    reposts: 123,
    visibility: 'public',
  },
  {
    id: '21',
    username: 'solanaGuru',
    profileImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7',
    isVerified: true,
    content: 'Solana ecosystem update: 50+ new projects launching this month. Bullish! 🚀 #Solana',
    timestamp: '13h ago',
    likes: 789,
    comments: 156,
    reposts: 234,
    visibility: 'public',
  },
  {
    id: '22',
    username: 'cryptoPrincess',
    profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2',
    isVerified: true,
    content: 'Portfolio update: Up 150% this month! 💅 Strategy is key, not luck. #CryptoQueen',
    timestamp: '15h ago',
    likes: 345,
    comments: 89,
    reposts: 67,
    visibility: 'followers',
  },
  {
    id: '23',
    username: 'diamondHands',
    profileImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d',
    isVerified: true,
    content: 'Been holding $SOL since $8. Diamond hands pay off! 💎🙌 Never selling.',
    timestamp: '16h ago',
    likes: 1234,
    comments: 234,
    reposts: 456,
    mentionedToken: 'SOL',
    visibility: 'public',
  },
  {
    id: '24',
    username: 'degenTrader',
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
    isVerified: false,
    content: 'Ape\'d into another shitcoin 🐒 This is either genius or complete madness. Probably both.',
    timestamp: '18h ago',
    likes: 123,
    comments: 45,
    reposts: 23,
    visibility: 'public',
  },
  {
    id: '25',
    username: 'moonBoy',
    profileImage: 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128',
    isVerified: false,
    content: 'Bullish on everything! 🚀 Bear market is over, bull run incoming! #ToTheMoon',
    timestamp: '20h ago',
    likes: 67,
    comments: 34,
    reposts: 12,
    visibility: 'public',
  },
  {
    id: '26',
    username: 'alphaWolf',
    profileImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e',
    isVerified: true,
    content: 'Chart analysis: https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800 $SOL breaking key resistance. Next stop $200! 📈',
    timestamp: '1d ago',
    likes: 567,
    comments: 89,
    reposts: 123,
    mentionedToken: 'SOL',
    visibility: 'public',
  },
  {
    id: '27',
    username: 'ghostxsol',
    profileImage: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61',
    isVerified: true,
    content: 'Trading setup: https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800 Perfect entry point for $JUP. Risk/reward is 1:5 🎯',
    timestamp: '1d ago',
    likes: 345,
    comments: 67,
    reposts: 89,
    mentionedToken: 'JUP',
    visibility: 'vip',
  },
  {
    id: '28',
    username: 'nftWhale',
    profileImage: 'https://images.unsplash.com/photo-1463453091185-61582044d556',
    isVerified: true,
    content: 'New NFT drop preview: https://images.unsplash.com/photo-1634973357973-f2ed2657db3c?w=800 This collection is going to be huge! Mint starts tomorrow 🎨',
    timestamp: '1d ago',
    likes: 789,
    comments: 156,
    reposts: 234,
    visibility: 'public',
  },
  {
    id: '29',
    username: 'solanaGuru',
    profileImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7',
    isVerified: true,
    content: 'DeFi protocol comparison: https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800 Which one offers the best yields? My analysis inside 📊',
    timestamp: '2d ago',
    likes: 456,
    comments: 123,
    reposts: 78,
    visibility: 'followers',
  },
  {
    id: '30',
    username: 'cryptoPrincess',
    profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2',
    isVerified: true,
    content: 'Portfolio diversification strategy: https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800 This is how I manage risk while maximizing returns 💼',
    timestamp: '2d ago',
    likes: 234,
    comments: 56,
    reposts: 34,
    visibility: 'public',
  },
];
